title: "Fahad"
theme: PaperMod
baseURL: "https://justfahad.me/"

copyright: |
  Made with â™¡ by [Ranger](https://github.com/Ranger-NF)

minify:
  disableXML: true

languages:
  en:
    languageName: "English"

taxonomies:
  series: series

params:
  env: production
  keywords: [Blog, Portfolio, PaperMod, About]
  defaultTheme: auto
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hideSummary: false
  showShareButtons: false
  ShareButtons: ["linkedin", "instagram", "x"]

  cover:
    hiddenInList: true

  profileMode:
    enabled: true
    title: "Mohammed Fahad"
    subtitle: |
      #### Kerala, India
      \
      Game Developer ğŸ®

      CSE Undergrad at **GEC Palakkad** ğŸ«

      Loves creating projects that are intuitive and fun ğŸ€

    imageUrl: "images/fahad-photo.png"

    buttons:
      - name: ğŸš€ Projects
        url: "/projects"
      - name: ğŸ“– Scrapbook
        url: "https://scrapbook.hackclub.com/Ranger"
      - name: ğŸ’­Posts
        url: "/posts"

  socialIcons:
    - name: instagram
      url: https://www.instagram.com/ranger_nf/
    - name: github
      url: "https://github.com/Ranger-NF"
    - name: linkedin
      url: https://www.linkedin.com/in/just-fahad/
    - name: itchio
      url: https://ranger-nf.itch.io/

markup:
  goldmark:
    parser:
      attribute:
        block: true
        title: true
