title: "The Breakthrough"
theme: PaperMod

minify:
  disableXML: true

languages:
  en:
    languageName: "English"

taxonomies:
  series: series

params:
  env: production
  keywords: [Blog, Portfolio, PaperMod, About]
  defaultTheme: auto
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowRssButtonInSectionTermList: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hideSummary: false
  ShowShareButtons: true

  homeInfoParams:
    Title: Tech Odyssey, Treasuring Earth;
    Content: |
    
        - Heyy fellow human! ğŸŒâœ¨
        
        - I'm **Fahad**, a.k.a. **Ranger**, and you've just stepped into **The Breakthrough**! ğŸš€ğŸ’»
        -
        - Let's dive into the world of **Linux**, **FOSS** (Free and Open Source Software), and all things tech, sprinkled with a dash of **love for Mother Earth**. ğŸŒ¿ Ready for an adventure?
        - Tighten your virtual hiking boots â€“ it's geek meets nature in the coolest fusion! ğŸŒŒğŸ”¥

        - #TechMeetsNature #TheBreakthrough
  socialIcons:
      - name: instagram
        url: https://www.instagram.com/ranger_nf/
      - name: github
        url: "https://github.com/Ranger-NF"

